workflows:
  ios-manual-signing:
    name: iOS Manual Signing
    instance_type: mac_mini_m2
    environment:
      vars:
        CERTIFICATE_PASSWORD: 123456     # coloque isso nos Secrets do CM
      ios_signing:
        certificate_path: ./certs/certificate.p12        # seu .p12
        certificate_password: $CERTIFICATE_PASSWORD
        provisioning_profile_path: ./certs/ZonaAzulAppStoreProfile.mobileprovision
        distribution_type: app_store
        bundle_identifier: br.com.w2esolucoes.zonaazul
      flutter: stable
      xcode: latest

    scripts:
      - name: Instalar dependências
        script: flutter pub get

      - name: Build IPA assinado
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build apk
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
