workflows:
  ios-appstore-build:
    name: iOS App Store Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        CERTIFICATE_PASSWORD: 123456
      ios_signing:
        distribution_type: app_store
        bundle_identifier: zonaazul-br.com.w2esolucoes.zonaazul
      flutter: stable
      xcode: latest
    scripts:
      - name: Importar certificado e perfil
        script: |
          keychain initialize
          keychain add-certificates --certificate ./certs/certificate.p12 --certificate-password $CERTIFICATE_PASSWORD
          keychain add-profile ./certs/ZonaAzulAppStoreProfile.mobileprovision
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa



  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build apk
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
