name: zona_azul
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.0 <4.0.0'



dependencies:
  shimmer:
  cupertino_icons: ^1.0.2
  slide_countdown: ^1.3.2
  get: 
  get_storage:
  get_cli:
  intl:
  easy_mask: ^2.0.1
  brasil_fields: 
  validatorless: ^1.2.1
  searchfield: ^0.9.0
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  circular_countdown_timer: ^0.2.0
  google_maps_flutter:
  #geolocator: ^5.1.1+1
  geolocator:
  geocoding:  
  permission_handler: ^11.0.1
  cupertino_radio_choice:
  custom_radio_grouped_button: ^2.1.1
  timezone:
  #permission_handler: ^9.2.0
  #permission_handler: 9.0.2
  flutter_svg: ^2.0.7
  #swipe_button_widget: ^0.0.2
  slide_to_confirm: ^1.1.0
  #slider_button: ^2.0.0
  slider_button:
  #  git: "https://github.com/da-nish/Slider-Button"
  #flutter_launcher_icons: ^0.9.2
  pdf:
  just_audio_background:
  printing:

#notificaçao estacionamento
  flutter_ringtone_player: 
  font_awesome_flutter: ^10.6.0
  awesome_notifications:
  awesome_notifications_core:
  waiter:
  #tela de introduçao
  introduction_screen: ^3.0.2
  


  
    
  
  



  flutter: 
    sdk: flutter
  animated_splash_screen: ^1.3.0
  vibration_web: ^1.6.5
  flutter_launcher_icons: ^0.13.1
  logger: ^2.0.2+1
  mockito: ^5.4.2
  quickalert: ^1.0.2
  location: ^5.0.3
  just_audio: ^0.9.36
  modal_progress_hud_nsn: ^0.5.1
  flutter_localizations:
    sdk: flutter
  retry: ^3.1.2
  local_auth: ^2.2.0
  another_flutter_splash_screen: ^1.2.0
  auto_size_text: ^3.0.0
  flutter_vector_icons: ^2.0.0
  alarm: ^5.1.3
  # alarm2: ^3.1.53
  # android_intent_plus: ^5.3.0

dev_dependencies: 
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ICON.PNG"
  #image_path: "assets/icons/ICON-ADAPTIVE.png"
  adaptive_icon_background: "#02acc2"
  adaptive_icon_foreground: "assets/icons/ICON-ADPATIVECorrigido.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/veiculos/celta.png
    - assets/iconCar.png
    - assets/car_splashscreen.riv
    - assets/car_splashscreenjuno.riv
    - assets/bancos/bancoDoBrasil.png
    - assets/bancos/caixa.png
    - assets/bancos/bradesco.png
    - assets/bancos/inter.png
    - assets/bancos/itau.png
    - assets/bancos/nubank.png
    - assets/bancos/santander.png
    - assets/icons/user.png
    - assets/notificationLargeIcon.png
    - assets/icons/carro.png
    - assets/icons/aviso.png
    - assets/alarm.mp3

